name: Build MainsailOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dpkg list
        run: sudo apt install -y transmission-cli

      - name: Download
        run: aria2c -d src/image/ --seed-time=0 https://downloads.raspberrypi.org/raspios_lite_armhf_latest.torrent

      - name: List files
        run: ls -lash src/image/
      
      #- name: Run Make Build
      #  run: make build