name: Build and Release MainsailOS - RapsiOS
on:
  release:
    types: [ published, prereleased, released ]

jobs:
  raspiosbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MainsailOS Project
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: repository
          submodules: true

      - name: Create dummy file
        run: echo test > file.txt

      - uses: actions/upload-artifact@v1
        with:
          name: file.txt
          path: file.txt

      - name: Upload RaspiOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: file.txt
          asset_name: file.txt
          asset_content_type: application/zip