name: Build MainsailOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dpkg list
        run: sudo dpkg -l

      - name: Download
        run: transmission-cli -w src/image/ 2020-08-20-raspios-buster-armhf-lite.zip.torrent

      - name: List files
        run: ls -lash src/image/
      
      #- name: Run Make Build
      #  run: make build