name: Build MainsailOS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download
        run: aria2c -d src/image/ --seed-time=0 https://downloads.raspberrypi.org/raspios_lite_armhf_latest.torrent

      - name: Cleanup Files
        run: |
          rm -rf src/image/*.zip.torrent
          mv src/image/*.zip src/image/raspbian_latest-raspbian.zip

      - name: Run the Build
        run: make build